"""create course_enrollments table

Revision ID: 01131647779a
Revises: 0bae70c0210d
Create Date: 2026-08-12 15:23:51.449619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01131647779a'
down_revision: Union[str, Sequence[str], None] = '0bae70c0210d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_resource_caches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('cached_text', sa.Text(), nullable=False),
    sa.Column('page_timestamp_map', sa.JSON(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('resource_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_resource_caches_id'), 'lesson_resource_caches', ['id'], unique=False)
    op.create_index(op.f('ix_lesson_resource_caches_resource_id'), 'lesson_resource_caches', ['resource_id'], unique=True)
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt_template', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_id'), 'prompt_templates', ['id'], unique=False)
    op.create_index(op.f('ix_prompt_templates_version'), 'prompt_templates', ['version'], unique=True)
    op.create_table('course_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ENROLLED', 'IN_PROGRESS', 'COMPLETED', 'DROPPED', name='enrollmentstatus'), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_student_course_enrollment')
    )
    op.create_index('idx_enrollment_course_id', 'course_enrollments', ['course_id'], unique=False)
    op.create_index('idx_enrollment_status', 'course_enrollments', ['status'], unique=False)
    op.create_index('idx_enrollment_student_id', 'course_enrollments', ['student_id'], unique=False)
    op.create_index(op.f('ix_course_enrollments_id'), 'course_enrollments', ['id'], unique=False)
    op.create_table('ai_generation_jobs',
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('progress_message', sa.String(length=255), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('current_chunk', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('total_words', sa.Integer(), nullable=False),
    sa.Column('estimated_duration_sec', sa.Integer(), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_ai_generation_jobs_job_id'), 'ai_generation_jobs', ['job_id'], unique=False)
    op.create_index(op.f('ix_ai_generation_jobs_lesson_id'), 'ai_generation_jobs', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_ai_generation_jobs_status'), 'ai_generation_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_ai_generation_jobs_teacher_id'), 'ai_generation_jobs', ['teacher_id'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'lesson_id', name='uq_student_lesson_progress')
    )
    op.create_index('idx_progress_completed', 'lesson_progress', ['completed'], unique=False)
    op.create_index('idx_progress_last_accessed', 'lesson_progress', ['last_accessed'], unique=False)
    op.create_index('idx_progress_lesson_id', 'lesson_progress', ['lesson_id'], unique=False)
    op.create_index('idx_progress_student_id', 'lesson_progress', ['student_id'], unique=False)
    op.create_index(op.f('ix_lesson_progress_id'), 'lesson_progress', ['id'], unique=False)
    op.create_table('student_bookmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'lesson_id', name='uq_student_bookmark')
    )
    op.create_index('idx_bookmark_lesson_id', 'student_bookmarks', ['lesson_id'], unique=False)
    op.create_index('idx_bookmark_student_id', 'student_bookmarks', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_bookmarks_id'), 'student_bookmarks', ['id'], unique=False)
    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_lesson_id', 'study_sessions', ['lesson_id'], unique=False)
    op.create_index('idx_session_started_at', 'study_sessions', ['started_at'], unique=False)
    op.create_index('idx_session_student_id', 'study_sessions', ['student_id'], unique=False)
    op.create_index(op.f('ix_study_sessions_id'), 'study_sessions', ['id'], unique=False)
    op.create_table('ai_generation_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('chunk_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('source_range', sa.String(length=255), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('questions_requested', sa.Integer(), nullable=False),
    sa.Column('questions_generated', sa.Integer(), nullable=False),
    sa.Column('duplicates_removed', sa.Integer(), nullable=False),
    sa.Column('confidence_avg', sa.Integer(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ai_generation_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generation_chunks_id'), 'ai_generation_chunks', ['id'], unique=False)
    op.create_index(op.f('ix_ai_generation_chunks_job_id'), 'ai_generation_chunks', ['job_id'], unique=False)
    op.create_table('ai_generation_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ai_generation_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generation_logs_id'), 'ai_generation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_generation_logs_job_id'), 'ai_generation_logs', ['job_id'], unique=False)
    op.create_table('ai_generation_questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=100), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('option_a', sa.Text(), nullable=True),
    sa.Column('option_b', sa.Text(), nullable=True),
    sa.Column('option_c', sa.Text(), nullable=True),
    sa.Column('option_d', sa.Text(), nullable=True),
    sa.Column('correct_option', sa.String(length=10), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('question_type', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('bloom_level', sa.String(length=50), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source_attribution', sa.String(length=255), nullable=True),
    sa.Column('ai_confidence', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('rejected_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['ai_generation_jobs.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generation_questions_id'), 'ai_generation_questions', ['id'], unique=False)
    op.create_index(op.f('ix_ai_generation_questions_job_id'), 'ai_generation_questions', ['job_id'], unique=False)
    op.create_table('assessment_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'question_id', name='uq_assessment_question')
    )
    op.create_index(op.f('ix_assessment_questions_assessment_id'), 'assessment_questions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_questions_id'), 'assessment_questions', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_questions_question_id'), 'assessment_questions', ['question_id'], unique=False)
    op.add_column('assessments', sa.Column('assessment_type', sa.Enum('QUIZ', 'PRACTICE', 'CHAPTER_TEST', 'MIDTERM', 'FINAL', name='assessmenttype'), nullable=False))
    op.add_column('assessments', sa.Column('scope', sa.Enum('LESSON', 'CHAPTER', 'COURSE', name='assessmentscope'), nullable=False))
    op.add_column('assessments', sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='assessmentstatus'), nullable=False))
    op.add_column('assessments', sa.Column('chapter_id', sa.Integer(), nullable=True))
    op.add_column('assessments', sa.Column('lesson_id', sa.Integer(), nullable=True))
    op.add_column('assessments', sa.Column('passing_score', sa.Integer(), nullable=False))
    op.add_column('assessments', sa.Column('max_attempts', sa.Integer(), nullable=False))
    op.add_column('assessments', sa.Column('shuffle_questions', sa.Boolean(), nullable=False))
    op.add_column('assessments', sa.Column('shuffle_options', sa.Boolean(), nullable=False))
    op.add_column('assessments', sa.Column('show_correct_answers', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_assessments_chapter_id'), 'assessments', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_assessments_course_id'), 'assessments', ['course_id'], unique=False)
    op.create_index(op.f('ix_assessments_lesson_id'), 'assessments', ['lesson_id'], unique=False)
    op.create_foreign_key(None, 'assessments', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key(None, 'assessments', 'chapters', ['chapter_id'], ['id'])
    op.drop_column('assessments', 'total_marks')
    op.drop_constraint(op.f('uq_uploaded_file_chunk'), 'document_chunks', type_='unique')
    op.add_column('questions', sa.Column('lesson_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('difficulty', sa.String(length=50), nullable=True))
    op.add_column('questions', sa.Column('bloom_level', sa.String(length=50), nullable=True))
    op.add_column('questions', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('correct_answer', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('is_ai_generated', sa.Boolean(), nullable=False))
    op.add_column('questions', sa.Column('ai_version', sa.String(length=50), nullable=True))
    op.add_column('questions', sa.Column('prompt_template_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.add_column('questions', sa.Column('source_attribution', sa.String(length=255), nullable=True))
    op.add_column('questions', sa.Column('ai_confidence', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('tokens_input', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('tokens_output', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('estimated_cost', sa.Float(), nullable=True))
    op.add_column('questions', sa.Column('usage_count', sa.Integer(), nullable=False))
    op.alter_column('questions', 'option_a',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('questions', 'option_b',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('questions', 'option_c',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('questions', 'option_d',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('questions', 'correct_option',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.create_index(op.f('ix_questions_lesson_id'), 'questions', ['lesson_id'], unique=False)
    op.drop_constraint(op.f('questions_assessment_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'lessons', ['lesson_id'], ['id'], ondelete='SET NULL')
    op.drop_column('questions', 'assessment_id')
    op.drop_index(op.f('ix_uploaded_files_course_id'), table_name='uploaded_files')
    op.drop_constraint(op.f('fk_uploaded_files_course_id'), 'uploaded_files', type_='foreignkey')
    op.create_foreign_key(None, 'uploaded_files', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploaded_files', type_='foreignkey')
    op.create_foreign_key(op.f('fk_uploaded_files_course_id'), 'uploaded_files', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_uploaded_files_course_id'), 'uploaded_files', ['course_id'], unique=False)
    op.add_column('questions', sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_assessment_id_fkey'), 'questions', 'assessments', ['assessment_id'], ['id'])
    op.drop_index(op.f('ix_questions_lesson_id'), table_name='questions')
    op.alter_column('questions', 'correct_option',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.alter_column('questions', 'option_d',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('questions', 'option_c',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('questions', 'option_b',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('questions', 'option_a',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('questions', 'usage_count')
    op.drop_column('questions', 'estimated_cost')
    op.drop_column('questions', 'tokens_output')
    op.drop_column('questions', 'tokens_input')
    op.drop_column('questions', 'ai_confidence')
    op.drop_column('questions', 'source_attribution')
    op.drop_column('questions', 'source_type')
    op.drop_column('questions', 'prompt_template_id')
    op.drop_column('questions', 'ai_version')
    op.drop_column('questions', 'is_ai_generated')
    op.drop_column('questions', 'correct_answer')
    op.drop_column('questions', 'explanation')
    op.drop_column('questions', 'bloom_level')
    op.drop_column('questions', 'difficulty')
    op.drop_column('questions', 'lesson_id')
    op.create_unique_constraint(op.f('uq_uploaded_file_chunk'), 'document_chunks', ['uploaded_file_id', 'chunk_index'], postgresql_nulls_not_distinct=False)
    op.add_column('assessments', sa.Column('total_marks', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_index(op.f('ix_assessments_lesson_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_course_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_chapter_id'), table_name='assessments')
    op.drop_column('assessments', 'show_correct_answers')
    op.drop_column('assessments', 'shuffle_options')
    op.drop_column('assessments', 'shuffle_questions')
    op.drop_column('assessments', 'max_attempts')
    op.drop_column('assessments', 'passing_score')
    op.drop_column('assessments', 'lesson_id')
    op.drop_column('assessments', 'chapter_id')
    op.drop_column('assessments', 'status')
    op.drop_column('assessments', 'scope')
    op.drop_column('assessments', 'assessment_type')
    op.drop_index(op.f('ix_assessment_questions_question_id'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_id'), table_name='assessment_questions')
    op.drop_index(op.f('ix_assessment_questions_assessment_id'), table_name='assessment_questions')
    op.drop_table('assessment_questions')
    op.drop_index(op.f('ix_ai_generation_questions_job_id'), table_name='ai_generation_questions')
    op.drop_index(op.f('ix_ai_generation_questions_id'), table_name='ai_generation_questions')
    op.drop_table('ai_generation_questions')
    op.drop_index(op.f('ix_ai_generation_logs_job_id'), table_name='ai_generation_logs')
    op.drop_index(op.f('ix_ai_generation_logs_id'), table_name='ai_generation_logs')
    op.drop_table('ai_generation_logs')
    op.drop_index(op.f('ix_ai_generation_chunks_job_id'), table_name='ai_generation_chunks')
    op.drop_index(op.f('ix_ai_generation_chunks_id'), table_name='ai_generation_chunks')
    op.drop_table('ai_generation_chunks')
    op.drop_index(op.f('ix_study_sessions_id'), table_name='study_sessions')
    op.drop_index('idx_session_student_id', table_name='study_sessions')
    op.drop_index('idx_session_started_at', table_name='study_sessions')
    op.drop_index('idx_session_lesson_id', table_name='study_sessions')
    op.drop_table('study_sessions')
    op.drop_index(op.f('ix_student_bookmarks_id'), table_name='student_bookmarks')
    op.drop_index('idx_bookmark_student_id', table_name='student_bookmarks')
    op.drop_index('idx_bookmark_lesson_id', table_name='student_bookmarks')
    op.drop_table('student_bookmarks')
    op.drop_index(op.f('ix_lesson_progress_id'), table_name='lesson_progress')
    op.drop_index('idx_progress_student_id', table_name='lesson_progress')
    op.drop_index('idx_progress_lesson_id', table_name='lesson_progress')
    op.drop_index('idx_progress_last_accessed', table_name='lesson_progress')
    op.drop_index('idx_progress_completed', table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index(op.f('ix_ai_generation_jobs_teacher_id'), table_name='ai_generation_jobs')
    op.drop_index(op.f('ix_ai_generation_jobs_status'), table_name='ai_generation_jobs')
    op.drop_index(op.f('ix_ai_generation_jobs_lesson_id'), table_name='ai_generation_jobs')
    op.drop_index(op.f('ix_ai_generation_jobs_job_id'), table_name='ai_generation_jobs')
    op.drop_table('ai_generation_jobs')
    op.drop_index(op.f('ix_course_enrollments_id'), table_name='course_enrollments')
    op.drop_index('idx_enrollment_student_id', table_name='course_enrollments')
    op.drop_index('idx_enrollment_status', table_name='course_enrollments')
    op.drop_index('idx_enrollment_course_id', table_name='course_enrollments')
    op.drop_table('course_enrollments')
    op.drop_index(op.f('ix_prompt_templates_version'), table_name='prompt_templates')
    op.drop_index(op.f('ix_prompt_templates_id'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    op.drop_index(op.f('ix_lesson_resource_caches_resource_id'), table_name='lesson_resource_caches')
    op.drop_index(op.f('ix_lesson_resource_caches_id'), table_name='lesson_resource_caches')
    op.drop_table('lesson_resource_caches')
    # ### end Alembic commands ###
