"""sync database schema with models

Revision ID: 5c52803e1540
Revises: 01131647779a
Create Date: 2026-08-12 16:41:15.329867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c52803e1540'
down_revision: Union[str, Sequence[str], None] = '01131647779a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('assessment_type', sa.Enum('QUIZ', 'PRACTICE', 'CHAPTER_TEST', 'MIDTERM', 'FINAL', name='assessmenttype'), nullable=False))
    op.add_column('assessments', sa.Column('scope', sa.Enum('LESSON', 'CHAPTER', 'COURSE', name='assessmentscope'), nullable=False))
    op.add_column('assessments', sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='assessmentstatus'), nullable=False))
    op.add_column('assessments', sa.Column('chapter_id', sa.Integer(), nullable=True))
    op.add_column('assessments', sa.Column('lesson_id', sa.Integer(), nullable=True))
    op.add_column('assessments', sa.Column('passing_score', sa.Integer(), nullable=False))
    op.add_column('assessments', sa.Column('max_attempts', sa.Integer(), nullable=False))
    op.add_column('assessments', sa.Column('shuffle_questions', sa.Boolean(), nullable=False))
    op.add_column('assessments', sa.Column('shuffle_options', sa.Boolean(), nullable=False))
    op.add_column('assessments', sa.Column('show_correct_answers', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_assessments_chapter_id'), 'assessments', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_assessments_course_id'), 'assessments', ['course_id'], unique=False)
    op.create_index(op.f('ix_assessments_lesson_id'), 'assessments', ['lesson_id'], unique=False)
    op.create_foreign_key(None, 'assessments', 'chapters', ['chapter_id'], ['id'])
    op.create_foreign_key(None, 'assessments', 'lessons', ['lesson_id'], ['id'])
    op.drop_column('assessments', 'total_marks')
    op.drop_constraint(op.f('uq_uploaded_file_chunk'), 'document_chunks', type_='unique')
    op.add_column('questions', sa.Column('lesson_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('difficulty', sa.String(length=50), nullable=True))
    op.add_column('questions', sa.Column('bloom_level', sa.String(length=50), nullable=True))
    op.add_column('questions', sa.Column('explanation', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('correct_answer', sa.Text(), nullable=True))
    op.add_column('questions', sa.Column('is_ai_generated', sa.Boolean(), nullable=False))
    op.add_column('questions', sa.Column('ai_version', sa.String(length=50), nullable=True))
    op.add_column('questions', sa.Column('prompt_template_id', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.add_column('questions', sa.Column('source_attribution', sa.String(length=255), nullable=True))
    op.add_column('questions', sa.Column('ai_confidence', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('tokens_input', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('tokens_output', sa.Integer(), nullable=True))
    op.add_column('questions', sa.Column('estimated_cost', sa.Float(), nullable=True))
    op.add_column('questions', sa.Column('usage_count', sa.Integer(), nullable=False))
    op.alter_column('questions', 'option_a',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('questions', 'option_b',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('questions', 'option_c',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('questions', 'option_d',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('questions', 'correct_option',
               existing_type=sa.VARCHAR(length=1),
               nullable=True)
    op.create_index(op.f('ix_questions_lesson_id'), 'questions', ['lesson_id'], unique=False)
    op.drop_constraint(op.f('questions_assessment_id_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'lessons', ['lesson_id'], ['id'], ondelete='SET NULL')
    op.drop_column('questions', 'assessment_id')
    op.drop_index(op.f('ix_uploaded_files_course_id'), table_name='uploaded_files')
    op.drop_constraint(op.f('fk_uploaded_files_course_id'), 'uploaded_files', type_='foreignkey')
    op.create_foreign_key(None, 'uploaded_files', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'uploaded_files', type_='foreignkey')
    op.create_foreign_key(op.f('fk_uploaded_files_course_id'), 'uploaded_files', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_uploaded_files_course_id'), 'uploaded_files', ['course_id'], unique=False)
    op.add_column('questions', sa.Column('assessment_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_assessment_id_fkey'), 'questions', 'assessments', ['assessment_id'], ['id'])
    op.drop_index(op.f('ix_questions_lesson_id'), table_name='questions')
    op.alter_column('questions', 'correct_option',
               existing_type=sa.VARCHAR(length=1),
               nullable=False)
    op.alter_column('questions', 'option_d',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('questions', 'option_c',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('questions', 'option_b',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('questions', 'option_a',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('questions', 'usage_count')
    op.drop_column('questions', 'estimated_cost')
    op.drop_column('questions', 'tokens_output')
    op.drop_column('questions', 'tokens_input')
    op.drop_column('questions', 'ai_confidence')
    op.drop_column('questions', 'source_attribution')
    op.drop_column('questions', 'source_type')
    op.drop_column('questions', 'prompt_template_id')
    op.drop_column('questions', 'ai_version')
    op.drop_column('questions', 'is_ai_generated')
    op.drop_column('questions', 'correct_answer')
    op.drop_column('questions', 'explanation')
    op.drop_column('questions', 'bloom_level')
    op.drop_column('questions', 'difficulty')
    op.drop_column('questions', 'lesson_id')
    op.create_unique_constraint(op.f('uq_uploaded_file_chunk'), 'document_chunks', ['uploaded_file_id', 'chunk_index'], postgresql_nulls_not_distinct=False)
    op.add_column('assessments', sa.Column('total_marks', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_constraint(None, 'assessments', type_='foreignkey')
    op.drop_index(op.f('ix_assessments_lesson_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_course_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_chapter_id'), table_name='assessments')
    op.drop_column('assessments', 'show_correct_answers')
    op.drop_column('assessments', 'shuffle_options')
    op.drop_column('assessments', 'shuffle_questions')
    op.drop_column('assessments', 'max_attempts')
    op.drop_column('assessments', 'passing_score')
    op.drop_column('assessments', 'lesson_id')
    op.drop_column('assessments', 'chapter_id')
    op.drop_column('assessments', 'status')
    op.drop_column('assessments', 'scope')
    op.drop_column('assessments', 'assessment_type')
    # ### end Alembic commands ###
